### ISSUE TITLE
Order confirmation message

### ISSUE THREAD

**Issue by joebusby** [firebearstudio/shapeshift-magento2#2]
When the ShapeShift extension is installed and disabled, the order confirmation page shows the message:
"Your order was placed with ShapeShift.io payment. "  despite the use of another payment mechanism.  I did not test the result when the extension is enabled and another payment mechanism is used.

**Comment by biotech** [comment]
Working on it to fix asap on the new version! Thank you!

**Comment by biotech** [comment]
Solved on last release https://github.com/firebearstudio/shapeshift-magento2/releases/tag/v1.0.12
