### ISSUE TITLE
No client-side validation that a currency is selected

### ISSUE THREAD

**Issue by JanisE** [firebearstudio/shapeshift-magento2#3]
On the checkout page, if I select the Shapeshift payment method but do not select a valid entry from "What currency do you want to pay?" select field, I do not get a message about being required to select a currency, but a message "There was an error creating your order, please try again in a few minutes. (0x03331202) Request: https://shapeshift.io/sendamount" instead.

**Comment by graffov87** [comment]
Thank you for your comment. We will fix

**Comment by graffov87** [comment]
It is fixed. ))

**Comment by JanisE** [comment]
Wow, that was quick! Thanks!
