### ISSUE TITLE
Could checkout when ETH is set as currency

### ISSUE THREAD

**Issue by xmav** [firebearstudio/shapeshift-magento2#7]
Steps to reproduce:
- Go to configuration (Stores=>Configuration=>Payment methods=>Shape Shift Payment)
- Set following values
** Enable => Yes
** What currency do you want to receive? => ETH
** Deposit Address => your address
** Allow currency => select all
- Go to frontend and try to checkout using Shape Shift

Actual result:
Call to `http://host/shapeshift/api/index` fails with 503
Debug message: "CoinMarketCap API error: id not found"

Expected result:
User friendly error message should be displayed on checkout page in case of error.

Notes:
Issue comes from different currency name used for\from api requests:
Call to `https://shapeshift.io/getcoins` gives ETH = ether. While `https://api.coinmarketcap.com/v1/ticker/{currency_id}` expect it to be "ethereum"
So wrong enpoint is used
`https://api.coinmarketcap.com/v1/ticker/ether/ `
intead of 
`https://api.coinmarketcap.com/v1/ticker/ethereum`

**Comment by biotech** [comment]
Thank you for the report, we will investigate!

**Comment by artemfb** [comment]
@xmav Issue was fixed.
